version: '3.8'

services:
  backend_db:
    image: mysql:8.0
    container_name: vulnerability
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
      container_name: vulnerability_security
      build:
        context: .
        dockerfile: ./Dockerfile
      env_file:
        - ./.env
      ports:
        - "8000:8000"
      volumes:
         - ./security_manager:/home/app/src
      depends_on:
        - backend_db

volumes:
  db_data:
    driver: local
